---
- name: systemd | Deploy the avise service
  copy:
    src: "systemd/avise_{{ se_deploy_type }}.service"
    dest: /etc/systemd/system/avise.service
    mode: 0644
  become: true
  notify:
    - Avi SE | Services | systemd | Daemon reload
    - Avi SE | Services | Restart the avise service
